services:
  backend:
    build: ./ai-express
    container_name: ai-backend
    env_file:
      - ./ai-express/.env
    ports:
      - "3000-3000"
  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend